id: node.project.field_screenshots
status: true
langcode: en
entity_type: node
bundle: project
label: Screenshots
description: ''
required: 0
default_value: {  }
default_value_function: ''
settings:
  file_directory: screenshots
  file_extensions: 'png gif jpg jpeg'
  max_filesize: 2MB
  max_resolution: 2000x2000
  min_resolution: 200x200
  alt_field: 1
  alt_field_required: 1
  title_field: 1
  title_field_required: 0
  default_image:
    fid: null
    alt: ''
    title: ''
    width: null
    height: null
field_type: image
