id: node.field_screenshots
uuid: 65ce6a64-2ae1-4d00-a300-da0908c4a92e
status: true
langcode: en
name: field_screenshots
entity_type: node
type: image
settings:
  uri_scheme: public
  default_image:
    fid: null
    alt: ''
    title: ''
    width: null
    height: null
  column_groups:
    file:
      label: File
      columns:
        - target_id
        - width
        - height
    alt:
      label: Alt
      translatable: true
    title:
      label: Title
      translatable: true
module: image
active: true
locked: false
cardinality: '-1'
translatable: false
indexes: {  }
