type: project
uuid: ee3efcd3-87ae-435b-bd33-51708186f307
name: Project
description: 'Some kind of project.'
help: ''
has_title: true
title_label: 'Title'
settings:
  node:
    preview: '0'
    options:
      status: status
      promote: promote
      sticky: 0
      revision: 0
    submitted: 1
status: true
langcode: en
